added error codes

diff --git a/src/main/app-resources/geocode/run b/src/main/app-resources/geocode/run
--- a/src/main/app-resources/geocode/run
+++ b/src/main/app-resources/geocode/run
@@ -29,26 +29,26 @@ function cleanExit ()
 {
   local retval=$?
   local msg=""
-  case "$retval" in
-    $SUCCESS) msg="Processing successfully concluded";;
-    $ERR_INGEST) msg="Failed to ingest the TerraSAR-X product";;
-    $ERR_MULTILOOK) msg="Failed to multi look";;
-    $ERR_RADCM) msg="Failed to rad";;
-    $ERR_GEOCODEB) msg="Failed to geocode back";;
-    $ERR_RAS) msg="Failed to convert raster";;
-    $ERR_GECMAP) msg="Failed to create geocode map";;
-    $ERR_RATIO) msg="Failed to calculate ratio";;
-    $ERR_RASPWR) msg="Failed to generate raster pwr";;
-    $ERR_GEOCODEB2) msg="Failed to geocode back";;
-    $ERR_RAS2) msg="Failed to convert raster";;
-  *) msg="Unknown error";;
+  case "${retval}" in
+    ${SUCCESS}) msg="Processing successfully concluded";;
+    ${ERR_INGEST}) msg="Failed to ingest the TerraSAR-X product";;
+    ${ERR_MULTILOOK}) msg="Failed to multi look";;
+    ${ERR_RADCM}) msg="Failed to rad";;
+    ${ERR_GEOCODEB}) msg="Failed to geocode back";;
+    ${ERR_RAS}) msg="Failed to convert raster";;
+    ${ERR_GECMAP}) msg="Failed to create geocode map";;
+    ${ERR_RATIO}) msg="Failed to calculate ratio";;
+    ${ERR_RASPWR}) msg="Failed to generate raster pwr";;
+    ${ERR_GEOCODEB2}) msg="Failed to geocode back";;
+    ${ERR_RAS2}) msg="Failed to convert raster";;
+    *) msg="Unknown error";;
   esac
 
   # clean up working space
   rm -fr ${TMPDIR}
 
-  [ "$retval" != "0" ] && ciop-log "ERROR" "Error $retval - $msg, processing aborted" || ciop-log "INFO" "$msg"
-  exit $retval
+  [ "${retval}" != "0" ] && ciop-log "ERROR" "Error ${retval} - ${msg}, processing aborted" || ciop-log "INFO" "${msg}"
+  exit ${retval}
 }
 
 trap cleanExit EXIT
@@ -81,7 +81,7 @@ function ingest() {
     ${cos} \
     ${TMPDIR}/${polarization}.slc.par \
     ${TMPDIR}/${polarization}.slc \
-    ${polarization} &> ${TMPDIR}/par_TX_SLC_${polarization}.log || return $ERR_INGEST 
+    ${polarization} &> ${TMPDIR}/par_TX_SLC_${polarization}.log || return ${ERR_INGEST} 
   done
 
 }
@@ -94,7 +94,7 @@ function mlook() {
       ${TMPDIR}/${polarization}.slc \
       ${TMPDIR}/${polarization}.slc.par \
       ${TMPDIR}/${polarization}.mli \
-      ${TMPDIR}/${polarization}.mli.par 6 4 &> ${TMPDIR}/multi_look_${polarization}.log || return 6
+      ${TMPDIR}/${polarization}.mli.par 6 4 &> ${TMPDIR}/multi_look_${polarization}.log || return ${ERR_MULTILOOK}
   done
 }
 
@@ -105,7 +105,7 @@ function radcm() {
     radcal_MLI \
       ${TMPDIR}/${polarization}.mli \
       ${TMPDIR}/${polarization}.slc.par - \
-      ${TMPDIR}/${polarization}.cmli - 0 0 1 0.0 - &> ${TMPDIR}/radcal_MLI_${polarization}.lop || return 8
+      ${TMPDIR}/${polarization}.cmli - 0 0 1 0.0 - &> ${TMPDIR}/radcal_MLI_${polarization}.lop || return ${ERR_RADCM}
   done
 }
 
@@ -120,7 +120,7 @@ function geocodeb() {
       ${TMPDIR}/${polarization}.cmli \
       ${r_samples} \
       ${TMPDIR}/DEM.lookup_table \
-      ${TMPDIR}/${polarization}.cmli.geocoded ${w} - 0 0 &> ${TMPDIR}/geocode_back_${polarization}.log || return 10
+      ${TMPDIR}/${polarization}.cmli.geocoded ${w} - 0 0 &> ${TMPDIR}/geocode_back_${polarization}.log || return ${ERR_GEOCODEB}
    done
 
 }
@@ -135,7 +135,7 @@ function ras() {
       ${TMPDIR}/${polarization}.cmli \
       ${range_samples} \
       1 0 1 1 - - - \
-      ${TMPDIR}/${polarization}.cmli.ras &> ${TMPDIR}/raspwr_${polarization}.log
+      ${TMPDIR}/${polarization}.cmli.ras &> ${TMPDIR}/raspwr_${polarization}.log || return ${ERR_RASPWR}
   done
 }
 
@@ -171,13 +171,13 @@ function main () {
       ${TMPDIR}/${pol_array[0]}.mli.par - \
       ${DEM_PAR} 0.0 \
       ${dem_seg_par} \
-      ${TMPDIR}/DEM.lookup_table 20 20 &> ${TMPDIR}/gec_map.log || return $?
+      ${TMPDIR}/DEM.lookup_table 20 20 &> ${TMPDIR}/gec_map.log || return ${ERR_GECMAP}
 
       width=$( cat ${dem_seg_par} | grep width | tr  -s " " | cut -d " " -f 2 )
       range_samples=$( cat ${TMPDIR}/${pol_array[0]}.mli.par | grep range_samples | tr  -s " " | cut -d " " -f 2 )
 
     ciop-log "INFO" "Geocoding of image data using lookup table values"
-      geocodeb ${range_samples} ${width} || return $?
+      geocodeb ${range_samples} ${width} || return ${ERR_GEOCODEB2}
 
     [ ${#pol_array[@]} == 2 ] && {   
       
@@ -186,7 +186,7 @@ function main () {
         ${TMPDIR}/${pol_array[0]}.cmli \
         ${TMPDIR}/${pol_array[1]}.cmli \
         ${TMPDIR}/${pol_array[0]}${pol_array[1]} \
-        ${range_samples} &> ${TMPDIR}/ratio.log || return $?
+        ${range_samples} &> ${TMPDIR}/ratio.log || return ${ERR_RATIO}
     }
 
     ciop-log "INFO" "Generate 8-bit greyscale raster image of intensity data"
@@ -199,14 +199,14 @@ function main () {
         ${TMPDIR}/${pol_array[0]}${pol_array[1]} \
         ${range_samples} \
         1 0 1 1 - - - \
-        ${TMPDIR}/${pol_array[0]}${pol_array[1]}.cmli.ras &> ${TMPDIR}/raspwr_${pol_array[0]}${pol_array[1]}.log || return $?
+        ${TMPDIR}/${pol_array[0]}${pol_array[1]}.cmli.ras &> ${TMPDIR}/raspwr_${pol_array[0]}${pol_array[1]}.log || return ${ERR_RASPWR}
 
       ciop-log "INFO" "Combine 3 raster images into a composite 24-bit RGB"
       ras_to_rgb \
         ${TMPDIR}/${pol_array[0]}.cmli.ras \
         ${TMPDIR}/${pol_array[1]}.cmli.ras \
         ${TMPDIR}/${pol_array[0]}${pol_array[1]}.cmli.ras \
-        ${TMPDIR}/RGB.bmp &> ${TMPDIR}/ras_to_rgb.log || return $? 
+        ${TMPDIR}/RGB.bmp &> ${TMPDIR}/ras_to_rgb.log || return ${ERR_RAS}
 
       ciop-log "INFO" "Geocoding of image data using lookup table values"
       geocode_back \
@@ -214,8 +214,9 @@ function main () {
         ${range_samples} \
         ${TMPDIR}/DEM.lookup_table \
         ${TMPDIR}/$( basename ${local_input} )_RGB.geocoded.bmp \
-        ${width} - 0 2 &> ${TMPDIR}/geocode_back_RGB.log || return $?
-     
+        ${width} - 0 2 &> ${TMPDIR}/geocode_back_RGB.log || return ${ERR_GEOCODEB2}
+      
+      ciop-log "INFO" "Publish geocoded bmp" 
       ciop-publish -m ${TMPDIR}/$( basename ${local_input} )_RGB.geocoded.bmp
 
     } || {
@@ -231,8 +232,9 @@ function main () {
         ${range_samples} \
         ${TMPDIR}/DEM.lookup_table \
         ${TMPDIR}/$( basename ${local_input} ).geo.bmp \
-        ${width} - 0 2 &> ${TMPDIR}/geocode_back_${pol_array[0]}_geo.log || return $? - 0 2
+        ${width} - 0 2 &> ${TMPDIR}/geocode_back_${pol_array[0]}_geo.log || return ${ERR_RAS2}
      
+      ciop-log "INFO" "Publish geocoded bmp" 
       ciop-publish -m ${TMPDIR}/$( basename ${local_input} ).geo.bmp
     }
   done
@@ -241,16 +243,21 @@ function main () {
 
 ciop-log "INFO" "Retrieving DEM"
 # retrieve the DEM
+
 mkdir -p ${TMPDIR}/workdir/dem
+# browse the DEM generation node results
 wps_result="$( ciop-browseresults -r ${CIOP_WF_RUN_ID} -j node_dem -w | tr -d '\r' | tr '\n' ';' | cut -d ";" -f 1)"
+
 # extract the result URL
 curl -L -o ${TMPDIR}/workdir/dem/dem.tgz "${wps_result}" 2> /dev/null
 tar xzf ${TMPDIR}/workdir/dem/dem.tgz -C ${TMPDIR}/workdir/dem/
 
+# export DEM and DEM.par path
 export DEM="$( find $TMPDIR/workdir/dem -name "*.dem" )"
 export DEM_PAR="$( find $TMPDIR/workdir/dem -name "*.dem.par" )"
 
-# GAMMA wants to write here:
+# GAMMA wants to write here, set the rights 
 chmod -R 777 ${TMPDIR}/workdir
 
+# invoke main function
 cat | main || exit $?
